baseURL = "https://nathanhuang.xyz/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Nathan Huang"
theme = "archie"
copyright = "© Nathan Huang"
pygmentsstyle = "monokai"
googleAnalytics = "G-XDJKM1BWRZ"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
ignoreErrors = ["error-missing-instagram-accesstoken"]
[params]
	mode="auto"
	useCDN=false
	subtitle = "欢迎！我是Nathan Huang，营销学博士在读，这里主要记录我对投资，写作，数据，营销的想法。"
  description = "欢迎！我是Nathan Huang，营销学博士在读，这里主要记录我对投资，写作，数据，营销的想法。"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nathanhuangzhi/"



[[params.social]]
icon = "rss"
icon_pack = "fa"
url = "/index.xml"

[[params.social]]
icon = "inbox"
icon_pack = "fa"
url = ""



# icon can be found https://www.fontawesomecheatsheet.com/


#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://github.com/athulcajay/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"
[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/post"
weight = 2

[[menu.main]]
name = "关于"
url = "/about"
weight = 3

[[menu.main]]
name = "标签"
url = "/tags"
weight = 4
